# ==============================================================================
# Datadog AWS Integration Role
# ==============================================================================

# IAM Role for Datadog AWS Integration
# Uses the external_id generated by Datadog (from datadog_integration_aws_account resource)
resource "aws_iam_role" "datadog_integration" {
  name = "DatadogAWSIntegrationRole"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          AWS = "arn:aws:iam::417141415827:root" # Datadog's AWS account (AP1 region)
        }
        Condition = {
          StringEquals = {
            "sts:ExternalId" = var.datadog_external_id
          }
        }
      }
    ]
  })

  tags = {
    Name    = "DatadogAWSIntegrationRole"
    Purpose = "Datadog AWS Integration"
  }
}

# Attach AWS-managed SecurityAudit policy (covers most read permissions)
resource "aws_iam_role_policy_attachment" "datadog_security_audit" {
  role       = aws_iam_role.datadog_integration.name
  policy_arn = "arn:aws:iam::aws:policy/SecurityAudit"
}

# Datadog AWS Integration Policy (additional permissions not in SecurityAudit)
resource "aws_iam_role_policy" "datadog_integration_policy" {
  name = "DatadogAWSIntegrationPolicy"
  role = aws_iam_role.datadog_integration.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          # Account
          "account:GetAccountInformation",
          "account:GetContactInformation",
          # Budgets
          "budgets:ViewBudget",
          # CloudWatch (additional)
          "cloudwatch:Describe*",
          "cloudwatch:Get*",
          "cloudwatch:List*",
          # ECS (additional)
          "ecs:Describe*",
          "ecs:List*",
          # IAM
          "iam:ListAccountAliases",
          # Logs (additional for log forwarding)
          "logs:DeleteSubscriptionFilter",
          "logs:DescribeDeliveries",
          "logs:DescribeDeliverySources",
          "logs:DescribeSubscriptionFilters",
          "logs:FilterLogEvents",
          "logs:GetDeliveryDestination",
          "logs:PutSubscriptionFilter",
          "logs:TestMetricFilter",
          # Organizations
          "organizations:Describe*",
          "organizations:List*",
          # Resource Groups
          "resource-groups:Get*",
          "resource-groups:List*",
          # S3 (for log forwarding)
          "s3:GetBucketLogging",
          "s3:GetBucketNotification",
          "s3:PutBucketNotification",
          # SNS (for notifications)
          "sns:GetSubscriptionAttributes",
          "sns:List*",
          "sns:ListPlatformApplications",
          "sns:Publish",
          # SQS
          "sqs:GetQueueUrl",
          "sqs:ListQueues",
          # Support
          "support:DescribeTrustedAdvisor*",
          "support:RefreshTrustedAdvisorCheck",
          # STS
          "sts:AssumeRole",
          # Tags
          "tag:GetResources",
          "tag:GetTagKeys",
          "tag:GetTagValues",
          # Events (for EventBridge)
          "events:CreateEventBus"
        ]
        Resource = "*"
      }
    ]
  })
}

# Output for Datadog integration
output "datadog_integration_role_arn" {
  description = "ARN of IAM Role for Datadog Integration"
  value       = aws_iam_role.datadog_integration.arn
}

# ==============================================================================
# ECS Roles
# ==============================================================================

# ECS Task Role
resource "aws_iam_role" "ecs_task_role" {
  name = "datadog-poc-ecs-task-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "ecs-tasks.amazonaws.com"
        }
      }
    ]
  })

  tags = {
    Name = "datadog-poc-ecs-task-role"
  }
}

# ECS Task Policy
resource "aws_iam_role_policy" "ecs_task_policy" {
  name = "datadog-poc-ecs-task-policy"
  role = aws_iam_role.ecs_task_role.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "ssm:GetParameter",
          "ssm:GetParameters"
        ]
        Resource = "arn:aws:ssm:${var.aws_region}:*:parameter/datadog-poc/*"
      }
    ]
  })
}

# ECS Execution Role
resource "aws_iam_role" "ecs_execution_role" {
  name = "datadog-poc-ecs-execution-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "ecs-tasks.amazonaws.com"
        }
      }
    ]
  })

  tags = {
    Name = "datadog-poc-ecs-execution-role"
  }
}

# Attach AWS Managed Policy
resource "aws_iam_role_policy_attachment" "ecs_execution_role_policy" {
  role       = aws_iam_role.ecs_execution_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}

# Additional Policy for SSM Parameter (Secrets)
resource "aws_iam_role_policy" "ecs_execution_ssm_policy" {
  name = "datadog-poc-ecs-execution-ssm-policy"
  role = aws_iam_role.ecs_execution_role.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "ssm:GetParameters"
        ]
        Resource = "arn:aws:ssm:${var.aws_region}:*:parameter/datadog-poc/*"
      }
    ]
  })
}
