# AWS Region
variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "ap-northeast-1"
}

# Datadog API Key
variable "dd_api_key" {
  description = "Datadog API Key"
  type        = string
  sensitive   = true
}

# Datadog External ID (from Datadog integration)
variable "datadog_external_id" {
  description = "External ID for Datadog AWS Integration (generated by Datadog)"
  type        = string
  sensitive   = true
}

# Application version for DD_VERSION tag
variable "app_version" {
  description = "Application version for DD_VERSION tag"
  type        = string
  default     = "1.0.0"
}

# Tenants configuration
variable "tenants" {
  description = "Tenant configurations"
  type = map(object({
    name        = string
    cpu         = number
    memory      = number
    priority    = number
    environment = string
  }))
}
